%% run_simulation.m -- All example simulations
% Runs all the simulations

clear all;
close all;
clc;

%% Update AET, just in case
update_aet()

%% Initialize the Advanced EEG Toolbox
aet_init
k = 1;

%% Set up scripts to run


% scripts(k).func = @simulation_data;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source_sine');
% scripts(k).vars = {cfg};
% k = k+1;

%% Ex1
% scripts(k).func = @simulation_ex1_snr;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source',...
%     'sim_beam',             'sim_beam_1',...
%     'sim_file_out',         'mult_cort_src_ex1_snr_eps_10');
% scripts(k).vars = {cfg};
% k = k+1;

scripts(k).func = @simulation_ex1_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source',...
    'sim_beam',             'sim_beam_3',...
    'sim_file_out',         'mult_cort_src_ex1_snr_eps_200');
scripts(k).vars = {cfg};
k = k+1;

% scripts(k).func = @simulation_ex1_epsilon;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source',...
%     'sim_beam',             'sim_beam_1',...
%     'sim_file_out',         'mult_cort_src_ex1_epsilon');
% scripts(k).vars = {cfg};
% k = k+1;

%% Ex2
% scripts(k).func = @simulation_ex2_snr;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source',...
%     'sim_beam',             'sim_beam_2',...
%     'sim_file_out',         'mult_cort_src_ex2_snr_eps_10');
% scripts(k).vars = {cfg};
% k = k+1;

% scripts(k).func = @simulation_ex2_epsilon;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source',...
%     'sim_beam',             'sim_beam_2',...
%     'sim_file_out',         'mult_cort_src_ex2_epsilon');
% scripts(k).vars = {cfg};
% k = k+1;

%% Sinusoid signal

% scripts(k).func = @simulation_data;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source_sine');
% scripts(k).vars = {cfg};
% k = k+1;

% scripts(k).func = @simulation_ex2_snr;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source_sine',...
%     'sim_beam',             'sim_beam_2',...
%     'sim_file_out',         'mult_cort_src_sine_ex2_snr_eps_10');
% scripts(k).vars = {cfg};
% k = k+1;

%% Parameter sweep

% scripts(k).func = @simulation_data;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source');
% scripts(k).vars = {cfg};
% k = k+1;

% scripts(k).func = @simulation_variations_all;
% cfg = struct(...
%     'sim_data',             'sim_data_1',...
%     'sim_vars',             'sim_vars_1',...
%     'sim_src_parameters',   'src_param_mult_cortical_source');
%     'sim_beam',             'sim_beam_2',...
% scripts(k).vars = {cfg};
% k = k+1;




%% Run the scripts
aet_run_scripts( scripts );
