%% plot_sim_vars_single_bem_eig_variations

%% Start Brainstorm
brainstorm.bstcust_start();

%%
% WARNING!!
% Manually delete the existing study

%% Common Parameters
snr = 0;
mismatch = true;
import = true;

%% Setup the config for single_bem_paper
cfg = [];
cfg.sim_vars_name = 'sim_vars_single_src_eig_variations_';
cfg.data_set = SimDataSetEEG(...
        'sim_data_bem_1_100t',...
        'single_cort_src_1',...
        snr,...
        'iter',1);
cfg.mismatch = mismatch;
if mismatch
    cfg.source_file_tags = {...
        'rmv_epsilon_50',...
        'rmv_epsilon_100',...
        'rmv_epsilon_150',...
        'rmv_epsilon_200',...
        'rmv_aniso',...
        'rmv_eig_post_0_epsilon_50',...
        'rmv_eig_post_0_epsilon_100',...
        'rmv_eig_post_0_epsilon_150',...
        'rmv_eig_post_0_epsilon_200',...
        'rmv_aniso_eig_post_0',...
        'rmv_eig_pre_cov_0_epsilon_0-0001',...
        'rmv_eig_pre_cov_0_epsilon_0-001',...
        'rmv_eig_pre_cov_0_epsilon_0-01',...
        'rmv_eig_pre_cov_0_epsilon_0-1',...
        'rmv_eig_pre_cov_0_epsilon_1',...
        'rmv_eig_pre_cov_0_epsilon_10',...
        'rmv_eig_pre_cov_0_epsilon_100',...
        'rmv_aniso_eig_pre_cov_0',...
        'rmv_eig_pre_leadfield_0_epsilon_0-0001',...
        'rmv_eig_pre_leadfield_0_epsilon_0-001',...
        'rmv_eig_pre_leadfield_0_epsilon_0-01',...
        'rmv_eig_pre_leadfield_0_epsilon_0-1',...
        'rmv_eig_pre_leadfield_0_epsilon_1',...
        'rmv_eig_pre_leadfield_0_epsilon_10',...
        'rmv_eig_pre_leadfield_0_epsilon_100',...
        'rmv_eig_pre_leadfield_0_epsilon_1000',...
        'rmv_aniso_eig_pre_leadfield_0',...
        'lcmv',...
        'lcmv_eig_0',...
        'lcmv_reg_eig'};
else
    cfg.source_file_tags = {...
        'rmv_epsilon_20',...
        'rmv_epsilon_50',...
        'rmv_eig_post_0_epsilon_20',...
        'rmv_eig_post_0_epsilon_50',...
        'rmv_eig_pre_cov_0_epsilon_20',...
        'rmv_eig_pre_cov_0_epsilon_50',...
        'lcmv',...
        'lcmv_eig_0',...
        'lcmv_reg_eig'};
end

%% Import the results for single_bem_paper
if import
    cfg = brainstorm.bstcust_import_auto(cfg);
else
    cfg.study_idx = brainstorm.bstcust_study_id_simdata(cfg);
end

%% Plot the results
brainstorm.bstcust_plot(cfg.study_idx, cfg.snr);

%% Close all plots
% brainstorm.bstcust_plot_close();