%% bstcust_import_auto
% Import data from beamformer analysis to Brainstorm

% bstcust_start

% Mismatch data
mismatch = false;

%% ==== SETUP STUDY ====
% sim_vars_name = 'sim_vars_single_src_paper_';
sim_vars_name = 'sim_vars_mult_src_paper_';
% sim_vars_name = 'sim_vars_distr_src_paper_';
% Get the data file
cfg_data = [];
cfg_data.sim_name = 'sim_data_bem_1_100t';
% cfg_data.source_name = 'single_cort_src_1';
cfg_data.source_name = 'mult_cort_src_8';
% cfg_data.source_name = 'distr_cort_src_2';
cfg_data.snr = '-10';
cfg_data.iteration = '1';

if mismatch
    % NOTE the condition name is built from the mismatch tag so only add one
    % mismatch at a time
%     mismatch_tags = {'perturb_1'};
%     mismatch_tags = {'perturb_2'};
    mismatch_tags = {'3sphere'};
    if exist('sim_vars_name','var')
        % Add suffix for sim_vars
        sim_vars_name = [sim_vars_name 'mismatched'];
    end
    % Check that only one mismatch is being analyzed at a time
    if length(mismatch_tags) > 1
        error('reb:brainstorm_import_auto',...
            'only one mismatch at a time please');
    end
else
    if exist('sim_vars_name','var')
        % Add suffix for sim_vars
        sim_vars_name = [sim_vars_name 'matched'];
    end
end

subject_name = 'Subject01';
% Set up the condition name
if mismatch
    condition_name = [cfg_data.sim_name '_'...
        cfg_data.source_name '_' mismatch_tags{1}];
else
    condition_name = [cfg_data.sim_name '_'...
        cfg_data.source_name];
end

fprintf('Condition name: %s \n',condition_name);

% Get the subject
subject = bst_get('Subject', subject_name, 1);
% Get the current conditions for our subject
studies = bst_get('ConditionsForSubject', subject.FileName);
% Check if the current condition already exists
study_exists = find(file_compare(studies, condition_name), 1);
if isempty(study_exists)
    disp('Adding condition');
    % Add a new condition
    db_add_condition(subject_name, condition_name);
end
% Get the study id
[~, study_idx] = bst_get('Study',...
    fullfile(subject_name,condition_name,'brainstormstudy.mat'));

%% ==== GET TEMPLATE DATA STRUCT FROM BRAINSTORM ====
% Get a template study
template_study = bst_get('Study',...
    fullfile(subject_name,'template_data','brainstormstudy.mat'));
protocol_info = bst_get('ProtocolInfo');

% Get the eeg data
template_eeg_file = fullfile(protocol_info.STUDIES,...
    template_study.Data.FileName);
eeg = load(template_eeg_file);

% Get the source results data
template_source_file = fullfile(protocol_info.STUDIES,...
    template_study.Result.FileName);
source = load(template_source_file);

%% ==== IMPORT EEG DATA TO BRAINSTORM ====
cfg = [];
cfg.data_file = db.get_full_file_name(cfg_data);
cfg.data_file_tag = ['snr_' cfg_data.snr '_' cfg_data.iteration];
cfg.eeg = eeg;
cfg.study_idx = study_idx;

% FIXME Check if files already exist, build in option to replace them as
% well.
cfg = brainstorm.prep_import_eeg_auto(cfg);

%% ==== IMPORT SOURCE RESULTS TO BRAINSTORM ====

cfg.source = source;
% Beamformer analyses to import
if ~isempty(strfind(sim_vars_name, 'mult_src_paper_matched'))
    cfg.tags = {...
        'rmv_epsilon_20',...
        'rmv_epsilon_50',...
        'rmv_eig_1_epsilon_20',...
        'rmv_eig_1_epsilon_50',...
        'lcmv',...
        'lcmv_eig_1',...
        'lcmv_reg_eig'};
elseif ~isempty(strfind(sim_vars_name, 'mult_src_paper_mismatched'))
    cfg.tags = {...
        'rmv_epsilon_50',...
        'rmv_epsilon_100',...
        'rmv_epsilon_150',...
        'rmv_epsilon_200',...
        'rmv_eig_1_epsilon_50',...
        'rmv_eig_1_epsilon_100',...
        'rmv_eig_1_epsilon_150',...
        'rmv_eig_1_epsilon_200',...
        'lcmv',...
        'lcmv_eig_1',...
        'lcmv_reg_eig'};
elseif ~isempty(strfind(sim_vars_name, 'paper_matched'))
    cfg.tags = {...
        'rmv_epsilon_20',...
        'rmv_epsilon_50',...
        'rmv_eig_0_epsilon_20',...
        'rmv_eig_0_epsilon_50',...
        'lcmv',...
        'lcmv_eig_0',...
        'lcmv_reg_eig'};
elseif ~isempty(strfind(sim_vars_name, 'paper_mismatched'))
    cfg.tags = {...
        'rmv_epsilon_50',...
        'rmv_epsilon_100',...
        'rmv_epsilon_150',...
        'rmv_epsilon_200',...
        'rmv_eig_0_epsilon_50',...
        'rmv_eig_0_epsilon_100',...
        'rmv_eig_0_epsilon_150',...
        'rmv_eig_0_epsilon_200',...
        'lcmv',...
        'lcmv_eig_0',...
        'lcmv_reg_eig'};
else
    cfg.tags = {'lcmv',...
        'lcmv_eig_1',...
        'lcmv_eig_2',...
        'lcmv_eig_3',...
        'lcmv_reg_eig',...
        'rmv_epsilon_50',...
        'rmv_epsilon_100',...
        ...'rmv_epsilon_150',...
        'rmv_epsilon_200',...
        ...'rmv_epsilon_250',...
        'rmv_epsilon_300',...
        ...'rmv_epsilon_350',...
        'rmv_epsilon_400',...
        'rmv_eig_1_epsilon_5',...
        'rmv_eig_1_epsilon_10',...
        'rmv_eig_1_epsilon_20',...
        'rmv_eig_1_epsilon_30',...
        'rmv_eig_1_epsilon_40'...
        'rmv_eig_1_epsilon_50',...
        'rmv_eig_1_epsilon_100',...
        ...'rmv_eig_1_epsilon_150',...
        'rmv_eig_1_epsilon_200',...
        ...'rmv_eig_1_epsilon_250',...
        'rmv_eig_1_epsilon_300',...
        ...'rmv_eig_1_epsilon_350',...
        'rmv_eig_1_epsilon_400'...
        };
end
if mismatch
    n_tags = length(cfg.tags);
    n_mismatch_tags = length(mismatch_tags);
    tmp_tags = {};
    for i=1:n_tags
        for j=1:n_mismatch_tags
            tmp_tags = [tmp_tags [cfg.tags{i} '_' mismatch_tags{j}]];
        end
    end
    cfg.tags = tmp_tags;
end

cfg = brainstorm.prep_import_source_auto(cfg);

disp(['Current study: ' num2str(study_idx)]);

%% ==== PLOT CURRENT RESULTS ====

% brainstorm_plot(study_idx);
% brainstorm_plot_close();
