function cfg = bstcust_import_auto(cfg)
%BSTCUST_IMPORT_AUTO Import data from beamformer analysis to Brainstorm
%   BSTCUST_IMPORT_AUTO(CFG)
%
%   cfg is a struct with the following fields
%       sim_vars_name   name of the sim_vars config
%       sim_name        name of simulation data config
%       source_name     name of the source config
%       snr             (string) specific snr to import
%       mismatch        (boolean) specify whether scenario is a mismatch,
%                       this adds the appropriate suffixes
%
%   Output
%   returns cfg with the study_idx field

% Start Brainstorm
brainstorm.bstcust_start();

sim_vars_name = cfg.sim_vars_name;

%% === CHECK FOR MISMATCH SCENARIO ===

% Mismatch data
mismatch = cfg.mismatch;

if mismatch
    % NOTE the condition name is built from the mismatch tag so only add one
    % mismatch at a time
%     mismatch_tags = {'perturb_1'};
%     mismatch_tags = {'perturb_2'};
    mismatch_tags = {'3sphere'};
    if exist('sim_vars_name','var')
        % Add suffix for sim_vars
        sim_vars_name = [sim_vars_name 'mismatched'];
    end
    % Check that only one mismatch is being analyzed at a time
    if length(mismatch_tags) > 1
        error('reb:brainstorm_import_auto',...
            'only one mismatch at a time please');
    end
else
    if exist('sim_vars_name','var')
        % Add suffix for sim_vars
        sim_vars_name = [sim_vars_name 'matched'];
    end
end

%% ==== SETUP STUDY ====
% Config for the data file
cfg_data = [];
cfg_data.sim_name = cfg.sim_name;
cfg_data.source_name = cfg.source_name;
cfg_data.snr = cfg.snr;
cfg_data.iteration = '1';

subject_name = 'Subject01';
% Set up the condition name
if mismatch
    condition_name = [cfg_data.sim_name '_'...
        cfg_data.source_name '_' mismatch_tags{1}];
else
    condition_name = [cfg_data.sim_name '_'...
        cfg_data.source_name];
end

fprintf('Condition name: %s \n',condition_name);

% Get the subject
subject = bst_get('Subject', subject_name, 1);
% Get the current conditions for our subject
studies = bst_get('ConditionsForSubject', subject.FileName);
% Check if the current condition already exists
study_exists = find(file_compare(studies, condition_name), 1);
if isempty(study_exists)
    disp('Adding condition');
    % Add a new condition
    db_add_condition(subject_name, condition_name);
end
% Get the study id
[~, cfg.study_idx] = bst_get('Study',...
    fullfile(subject_name,condition_name,'brainstormstudy.mat'));

%% ==== GET TEMPLATE DATA STRUCT FROM BRAINSTORM ====
% Get a template study
template_study = bst_get('Study',...
    fullfile(subject_name,'template_data','brainstormstudy.mat'));
protocol_info = bst_get('ProtocolInfo');

% Get the eeg data
template_eeg_file = fullfile(protocol_info.STUDIES,...
    template_study.Data.FileName);
eeg = load(template_eeg_file);

% Get the source results data
template_source_file = fullfile(protocol_info.STUDIES,...
    template_study.Result.FileName);
source = load(template_source_file);

%% ==== IMPORT EEG DATA TO BRAINSTORM ====
cfg_db = [];
cfg_db.data_file = db.get_full_file_name(cfg_data);
cfg_db.data_file_tag = ['snr_' cfg_data.snr '_' cfg_data.iteration];
cfg_db.eeg = eeg;
cfg_db.study_idx = cfg.study_idx;

% FIXME Check if files already exist, build in option to replace them as
% well.
cfg_db = brainstorm.prep_import_eeg_auto(cfg_db);

%% ==== IMPORT SOURCE RESULTS TO BRAINSTORM ====

cfg_db.source = source;
% Beamformer analyses to import
if ~isempty(strfind(sim_vars_name, 'mult_src_paper_matched'))
    % Corresponds to sim_vars configs
    %   sim_vars_mult_src_paper_matched
    cfg_db.tags = {...
        'rmv_epsilon_20',...
        'rmv_epsilon_50',...
        'rmv_eig_1_epsilon_20',...
        'rmv_eig_1_epsilon_50',...
        'lcmv',...
        'lcmv_eig_1',...
        'lcmv_reg_eig'};
elseif ~isempty(strfind(sim_vars_name, 'mult_src_paper_mismatched'))
    % Corresponds to sim_vars configs
    %   sim_vars_mult_src_paper_mismatched
    cfg_db.tags = {...
        'rmv_epsilon_50',...
        'rmv_epsilon_100',...
        'rmv_epsilon_150',...
        'rmv_epsilon_200',...
        'rmv_aniso',...        
        'rmv_eig_1_epsilon_50',...
        'rmv_eig_1_epsilon_100',...
        'rmv_eig_1_epsilon_150',...
        'rmv_eig_1_epsilon_200',...
        'rmv_aniso_eig_1',...
        'lcmv',...
        'lcmv_eig_1',...
        'lcmv_reg_eig'};
elseif ~isempty(strfind(sim_vars_name, 'paper_matched'))
    % Corresponds to sim_vars configs
    %   sim_vars_single_src_paper_matched
    %   sim_vars_distr_src_paper_matched
    cfg_db.tags = {...
        'rmv_epsilon_20',...
        'rmv_epsilon_50',...
        'rmv_eig_0_epsilon_20',...
        'rmv_eig_0_epsilon_50',...
        'lcmv',...
        'lcmv_eig_0',...
        'lcmv_reg_eig'};
elseif ~isempty(strfind(sim_vars_name, 'paper_mismatched'))
    % Corresponds to sim_vars configs
    %   sim_vars_single_src_paper_mismatched
    %   sim_vars_distr_src_paper_mismatched
    cfg_db.tags = {...
        'rmv_epsilon_50',...
        'rmv_epsilon_100',...
        'rmv_epsilon_150',...
        'rmv_epsilon_200',...
        'rmv_aniso',...
        'rmv_eig_0_epsilon_50',...
        'rmv_eig_0_epsilon_100',...
        'rmv_eig_0_epsilon_150',...
        'rmv_eig_0_epsilon_200',...
        'rmv_aniso_eig_0',...
        'lcmv',...
        'lcmv_eig_0',...
        'lcmv_reg_eig'};
elseif ~isempty(strfind(sim_vars_name, 'mult_src_basic'))
    cfg_db.tags = {...
        'lcmv',...
        'rmv_epsilon_0-01',...
        'rmv_epsilon_5',...
        'rmv_aniso'};
else
    % Corresponds to whatever random sim_vars config
    cfg_db.tags = {'lcmv',...
        'lcmv_eig_1',...
        'lcmv_eig_2',...
        'lcmv_eig_3',...
        'lcmv_reg_eig',...
        'rmv_epsilon_50',...
        'rmv_epsilon_100',...
        ...'rmv_epsilon_150',...
        'rmv_epsilon_200',...
        ...'rmv_epsilon_250',...
        'rmv_epsilon_300',...
        ...'rmv_epsilon_350',...
        'rmv_epsilon_400',...
        'rmv_eig_1_epsilon_5',...
        'rmv_eig_1_epsilon_10',...
        'rmv_eig_1_epsilon_20',...
        'rmv_eig_1_epsilon_30',...
        'rmv_eig_1_epsilon_40'...
        'rmv_eig_1_epsilon_50',...
        'rmv_eig_1_epsilon_100',...
        ...'rmv_eig_1_epsilon_150',...
        'rmv_eig_1_epsilon_200',...
        ...'rmv_eig_1_epsilon_250',...
        'rmv_eig_1_epsilon_300',...
        ...'rmv_eig_1_epsilon_350',...
        'rmv_eig_1_epsilon_400'...
        };
end
if mismatch
    n_tags = length(cfg_db.tags);
    n_mismatch_tags = length(mismatch_tags);
    tmp_tags = {};
    for i=1:n_tags
        for j=1:n_mismatch_tags
            tmp_tags = [tmp_tags [cfg_db.tags{i} '_' mismatch_tags{j}]];
        end
    end
    cfg_db.tags = tmp_tags;
end

cfg_db = brainstorm.prep_import_source_auto(cfg_db);

disp(['Current study: ' num2str(cfg.study_idx)]);

%% ==== PLOT CURRENT RESULTS ====

% brainstorm.bstcust_plot(cfg.study_idx, cfg_data.snr);
% brainstorm.bstcust_plot_close();
end