%% metric_analysis_sinr_mult17_lag40_eigvariations_mini

force = true;

%% Compute sinr
params = [];
k = 1;

params(k).beamformer_configs = {...
    'rmv_epsilon_50_3sphere',...
    'rmv_epsilon_100_3sphere',...
    'rmv_epsilon_150_3sphere',...
    'rmv_epsilon_200_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_filter_0_3sphere',...
    'lcmv_eig_filter_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'iso';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_epsilon_100_3sphere',...
    'rmv_epsilon_150_3sphere',...
    'rmv_epsilon_200_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_100_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_150_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_200_3sphere',...
    'rmv_aniso_eig_pre_cov_1_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_cov_0_3sphere',...
    'lcmv_eig_cov_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'eig-pre-cov-lcmv';
k = k+1;

for i=1:length(params)
    plot_sinr_vs_snr_group(...
        'sim_data_bem_1_100t',...
        'mult_cort_src_17_lag40',...
        params(i).beamformer_configs,...
        295,...
        'savetag',params(i).tag,...
        'matched',false,...
        'flip',false,...
        'iteration',1,...
        'snrs',-20:10:20,...
        'force',force...
        );
    
    plot_sinr_vs_snr_group(...
        'sim_data_bem_1_100t',...
        'mult_cort_src_17_lag40',...
        params(i).beamformer_configs,...
        400,...
        'savetag',params(i).tag,...
        'matched',false,...
        'flip',true,...
        'iteration',1,...
        'snrs',-20:10:20,...
        'force',force...
        );
end