%% metric_analysis_sinr_mult17_lag40_eigvariations_mini

%% Data
% To generate data run the following script:

% run_sim_vars_bem_mult17_lag40_locs2_eigvariations

%% Compute sinr
force = true;
params = [];
k = 1;

params(k).beamformer_configs = {...
    'rmv_epsilon_50_locs2_3sphere',...
    'rmv_epsilon_100_locs2_3sphere',...
    'rmv_epsilon_150_locs2_3sphere',...
    'rmv_epsilon_200_locs2_3sphere',...
    'rmv_aniso_locs2_3sphere',...
    'lcmv_locs2_3sphere',...
    'lcmv_eig_filter_0_locs2_3sphere',...
    'lcmv_eig_filter_1_locs2_3sphere',...
    'lcmv_reg_eig_locs2_3sphere',...
    };
params(k).tag = 'iso';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_epsilon_100_locs2_3sphere',...
    'rmv_epsilon_150_locs2_3sphere',...
    'rmv_epsilon_200_locs2_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_100_locs2_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_150_locs2_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_200_locs2_3sphere',...
    'rmv_aniso_eig_pre_cov_1_locs2_3sphere',...
    'rmv_aniso_locs2_3sphere',...
    'lcmv_locs2_3sphere',...
    'lcmv_eig_cov_0_locs2_3sphere',...
    'lcmv_eig_cov_1_locs2_3sphere',...
    'lcmv_reg_eig_locs2_3sphere',...
    };
params(k).tag = 'eig-pre-cov-lcmv';
k = k+1;

for i=1:length(params)
    
    data_set = SimDataSetEEG(...
        'sim_data_bem_1_100t',...
        'mult_cort_src_17_lag40',...
        0,...
        'iter',1);
    
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        295,...
        'savetag',params(i).tag,...
        'matched',false,...
        'metricx','input snr',...
        'metricy','output sinr',...
        'snrs',-20:10:20,...
        'force',force...
        );
    
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        400,...
        'savetag',params(i).tag,...
        'matched',false,...
        'metricx','input snr',...
        'metricy','output isnr',...
        'snrs',-20:10:20,...
        'force',force...
        );
end
