%% metric_analysis_sinr_mult17_lag40

%% Data
% To generate data run the following script:

% run_sim_vars_bem_mult17_lag40_locs2

%% Compute sinr
force = true;
params = [];
k = 1;

params(k).beamformer_configs = {...
    'rmv_epsilon_20_locs2',...
    'rmv_eig_pre_cov_0_epsilon_20_locs2',...
    'rmv_eig_pre_cov_1_epsilon_20_locs2',...
    'lcmv_locs2',...
    'lcmv_eig_cov_0_locs2',...
    'lcmv_eig_cov_1_locs2',...
    'lcmv_reg_eig_locs2',...
    };
params(k).tag = '-final';
params(k).matched = true;
k = k+1;

% comparison of lcmv eigs in matched scenario
params(k).beamformer_configs = {...
    'rmv_epsilon_20_locs2',...
    'rmv_eig_pre_cov_1_epsilon_20_locs2',...
    'lcmv_locs2',...
    'lcmv_eig_leadfield_1_locs2',...
    'lcmv_eig_cov_1_locs2',...
    'lcmv_eig_filter_1_locs2',...
    'lcmv_reg_eig_locs2',...
    };
params(k).tag = '-lcmv';
params(k).matched = true;
k = k+1;

params(k).beamformer_configs = {...
    'rmv_epsilon_100_locs2_3sphere',...
    'rmv_epsilon_150_locs2_3sphere',...
    'rmv_epsilon_200_locs2_3sphere',...
    ...'rmv_eig_pre_cov_0_epsilon_100_locs2_3sphere',...
    ...'rmv_eig_pre_cov_1_epsilon_100_locs2_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_150_locs2_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_150_locs2_3sphere',...
    ...'rmv_eig_pre_cov_0_epsilon_200_locs2_3sphere',...
    ...'rmv_eig_pre_cov_1_epsilon_200_locs2_3sphere',...
    'rmv_aniso_eig_pre_cov_1_locs2_3sphere',...
    'rmv_aniso_locs2_3sphere',...
    'lcmv_locs2_3sphere',...
    'lcmv_eig_cov_0_locs2_3sphere',...
    'lcmv_eig_cov_1_locs2_3sphere',...
    'lcmv_reg_eig_locs2_3sphere',...
    };
params(k).tag = '-final';
params(k).matched = false;
k = k+1;

% params(k).beamformer_configs = {...
%     'rmv_epsilon_100_locs2_3sphere',...
%     'rmv_epsilon_150_locs2_3sphere',...
%     'rmv_epsilon_200_locs2_3sphere',...
%     'rmv_eig_pre_cov_0_epsilon_100_locs2_3sphere',...
%     'rmv_eig_pre_cov_0_epsilon_150_locs2_3sphere',...
%     'rmv_eig_pre_cov_0_epsilon_200_locs2_3sphere',...
%     'rmv_eig_pre_cov_1_epsilon_100_locs2_3sphere',...
%     'rmv_eig_pre_cov_1_epsilon_150_locs2_3sphere',...
%     'rmv_eig_pre_cov_1_epsilon_200_locs2_3sphere',...
%     };
% params(k).tag = '-eps-variations';
% params(k).matched = false;
% k = k+1;

for i=1:length(params)
    data_set = SimDataSetEEG(...
        'sim_data_bem_1_100t',...
        'mult_cort_src_17_lag40',...
        0,...
        'iter',1);
    
    % signal location, oSINR vs iSNR
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        295,...
        'savetag',params(i).tag,...
        'matched',params(i).matched,...
        'metricx','snr-input',...
        'metricy','sinr-beamformer-output',...
        'snrs',-20:5:20,...
        'force',force...
        );
    
    % signal location, oSNR vs iSNR
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        295,...
        'savetag',params(i).tag,...
        'matched',params(i).matched,...
        'metricx','snr-input',...
        'metricy', 'snr-beamformer-output',...
        'snrs',-20:5:20,...
        'force',force...
        );
    
    % interference location, oISNR vs iSNR
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        400,...
        'savetag',params(i).tag,...
        'matched',params(i).matched,...
        'metricx','snr-input',...
        'metricy','isnr-beamformer-output',...
        'snrs',-20:5:20,...
        'force',force...
        );
end
