%% metric_analysis_sinr_mult17_lag40_eigvariations

%% Compute sinr
params = [];
k = 1;

params(k).beamformer_configs = {...
    'rmv_epsilon_50_3sphere',...
    'rmv_epsilon_100_3sphere',...
    'rmv_epsilon_150_3sphere',...
    'rmv_epsilon_200_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_eig_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'iso';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_eig_post_0_epsilon_50_3sphere',...
    'rmv_eig_post_0_epsilon_100_3sphere',...
    'rmv_eig_post_0_epsilon_150_3sphere',...
    'rmv_eig_post_0_epsilon_200_3sphere',...
    'rmv_aniso_eig_0_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_eig_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'eig-post-0';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_eig_post_1_epsilon_50_3sphere',...
    'rmv_eig_post_1_epsilon_100_3sphere',...
    'rmv_eig_post_1_epsilon_150_3sphere',...
    'rmv_eig_post_1_epsilon_200_3sphere',...
    'rmv_aniso_eig_1_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_eig_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'eig-post-1';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_eig_pre_cov_0_epsilon_1-000000e-04_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_1-000000e-03_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_1-000000e-02_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_1-000000e-01_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_1_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_10_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_100_3sphere',...
    'rmv_aniso_pre_cov_0_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_eig_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'eig-pre-cov-0';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_eig_pre_cov_1_epsilon_1-000000e-04_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_1-000000e-03_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_1-000000e-02_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_1-000000e-01_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_1_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_10_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_100_3sphere',...
    'rmv_aniso_pre_cov_1_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_eig_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'eig-pre-cov-1';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_eig_pre_leadfield_0_epsilon_1-000000e-04_3sphere',...
    'rmv_eig_pre_leadfield_0_epsilon_1-000000e-03_3sphere',...
    'rmv_eig_pre_leadfield_0_epsilon_1-000000e-02_3sphere',...
    'rmv_eig_pre_leadfield_0_epsilon_1-000000e-02_3sphere',...
    'rmv_eig_pre_leadfield_0_epsilon_1_3sphere',...
    'rmv_eig_pre_leadfield_0_epsilon_10_3sphere',...
    'rmv_eig_pre_leadfield_0_epsilon_100_3sphere',...
    'rmv_aniso_pre_leadfield_0_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_eig_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'eig-pre-lf-0';
k = k+1;

params(k).beamformer_configs = {...
    'rmv_eig_pre_leadfield_1_epsilon_1-000000e-04_3sphere',...
    'rmv_eig_pre_leadfield_1_epsilon_1-000000e-03_3sphere',...
    'rmv_eig_pre_leadfield_1_epsilon_1-000000e-02_3sphere',...
    'rmv_eig_pre_leadfield_1_epsilon_1-000000e-01_3sphere',...
    'rmv_eig_pre_leadfield_1_epsilon_1_3sphere',...
    'rmv_eig_pre_leadfield_1_epsilon_10_3sphere',...
    'rmv_eig_pre_leadfield_1_epsilon_100_3sphere',...
    'rmv_aniso_pre_leadfield_1_3sphere',...
    'rmv_aniso_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_eig_1_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = 'eig-pre-lf-1';
k = k+1;

locations = [295,400];

for i=1:length(params)
    for j=1:length(locations)
        plot_sinr_vs_snr_group(...
            'sim_data_bem_1_100t',...
            'mult_cort_src_17_lag40',...
            params(i).beamformer_configs,...
            locations(j),...
            'savetag',params(i).tag,...
            'matched',false,...
            'flip',false,...
            'iteration',1,...
            'snrs',-20:10:20 ...
            );
    end
end