%% metric_analysis_sinr_single

%% Set up different metrics to calculate
% Single source results with 1 iteration

source_names = {...
    'single_cort_src_1',...
    };
    
snrs = -20:10:20;
location_idx = 1:501;
cfg = [];
cfg.force = false;
% cfg.force = true;
cfg.save_fig = true;

% Loop through source names
for j=1:length(source_names)
    
    %% ==== MATCHED LEADFIELD ====
    % Set up beamformer data sets to process
    beam_cfgs_matched = {...
        'rmv_epsilon_20_locs2',...
        ...'rmv_epsilon_50_locs2',...
        'rmv_eig_pre_cov_0_epsilon_20_locs2',...
        'rmv_eig_post_0_epsilon_20_locs2',...
        ...'rmv_eig_post_0_epsilon_50_locs2',...
        'lcmv_locs2',...
        'lcmv_eig_0_locs2',...
        'lcmv_reg_eig_locs2',...
        };
    
    cfg.beam_cfgs = beam_cfgs_matched;
    
    % Set up simulation info
    cfg.data_set = SimDataSetEEG(...
        'sim_data_bem_1_100t',...
    	source_names{j},...
        0,...
        'iter',1);
    cfg.snrs = snrs;
    cfg.save_tag = 'matched';
    
    %% Location: 295
    cfg.metrics.location_idx = 295;
    
    % Set up metric
    cfg.metric_x = 'input snr';
    cfg.metric_y = 'output sinr';
    % Compute SINR
    cfg = compute_metric_output_vs_input(cfg);
    % Plot SINR
    plot_metric_output_vs_input(cfg);
    
end

% Loop through source names
for j=1:length(source_names)
    
    %% ==== MISMATCHED LEADFIELD ====
    % Set up beamformer data sets to process
    beam_cfgs_mismatched = {...
        ...'rmv_epsilon_50_locs2_3sphere',...
        'rmv_epsilon_100_locs2_3sphere',...
        'rmv_epsilon_150_locs2_3sphere',...
        'rmv_epsilon_200_locs2_3sphere',...
        ...'rmv_epsilon_250_locs2_3sphere',...
        ...'rmv_epsilon_300_locs2_3sphere',...
        'rmv_aniso_locs2_3sphere',...
        'rmv_eig_pre_cov_0_epsilon_150_locs2_3sphere',...
        'rmv_eig_pre_cov_0_epsilon_200_locs2_3sphere',...
        ...'rmv_eig_post_0_epsilon_50_locs2_3sphere',...
        ...'rmv_eig_post_0_epsilon_100_locs2_3sphere',...
        'rmv_eig_post_0_epsilon_150_locs2_3sphere',...
        'rmv_eig_post_0_epsilon_200_locs2_3sphere',...
        ...'rmv_aniso_eig_0_locs2_3sphere',...
        'lcmv_locs2_3sphere',...
        'lcmv_eig_0_locs2_3sphere',...
        'lcmv_reg_eig_locs2_3sphere'};
    
    cfg.beam_cfgs = beam_cfgs_mismatched;
    
    % Set up simulation info
    cfg.data_set = SimDataSetEEG(...
        'sim_data_bem_1_100t',...
    	source_names{j},...
        0,...
        'iter',1);
    cfg.snrs = snrs;
    cfg.save_tag = 'mismatched';
    
    %% Location: 295
    cfg.metrics.location_idx = 295;
    
    % Set up metric
    cfg.metric_x = 'input snr';
    cfg.metric_y = 'output sinr';
    % Compute SINR
    cfg = compute_metric_output_vs_input(cfg);
    % Plot SINR
    plot_metric_output_vs_input(cfg);
    
end
