function metric_analysis_sinr_mult(sim_name,source_name)

force = true;

%% Compute sinr
params = [];
k = 1;

% FIXME pre cov or pre leadfield??
params(k).beamformer_configs = {...
    'rmv_epsilon_20_locs2',...
    'rmv_eig_pre_cov_0_epsilon_20_locs2',...
    'rmv_eig_pre_cov_1_epsilon_20_locs2',...
    'lcmv_locs2',...
    'lcmv_eig_cov_0_locs2',...
    'lcmv_eig_cov_1_locs2',...
    ...'lcmv_eig_filter_0_locs2',...
    ...'lcmv_eig_filter_1_locs2',...
    'lcmv_reg_eig'
    };
params(k).tag = '-final';
params(k).matched = true;
k = k+1;

% comparison of lcmv eigs in matched scenario
params(k).beamformer_configs = {...
    'rmv_epsilon_20_locs2',...
    'lcmv_locs2',...
    'lcmv_eig_leadfield_0_locs2',...
    'lcmv_eig_leadfield_1_locs2',...
    'lcmv_eig_cov_0_locs2',...
    'lcmv_eig_cov_1_locs2',...
    'lcmv_eig_filter_0_locs2',...
    'lcmv_eig_filter_1_locs2',...
    'lcmv_eig_cov_leadfield_0_locs2',...
    'lcmv_eig_cov_leadfield_1_locs2',...
    'lcmv_reg_eig_locs2',...
    };
params(k).tag = '-lcmv';
params(k).matched = true;
k = k+1;

% FIXME pre cov or pre leadfield??
params(k).beamformer_configs = {...
    ...'rmv_epsilon_100_locs2_3sphere',...
    ...'rmv_eig_pre_cov_0_epsilon_100_locs2_3sphere',...
    ...'rmv_eig_pre_cov_1_epsilon_100_locs2_3sphere',...
    'rmv_epsilon_150_locs2_3sphere',...
    'rmv_eig_pre_leadfield_0_epsilon_150_locs2_3sphere',...
    'rmv_eig_pre_leadfield_1_epsilon_150_locs2_3sphere',...
    'rmv_eig_pre_cov_0_epsilon_150_locs2_3sphere',...
    'rmv_eig_pre_cov_1_epsilon_150_locs2_3sphere',...
    ...'rmv_epsilon_200_locs2_3sphere',...
    ...'rmv_eig_pre_cov_0_epsilon_200_locs2_3sphere',...
    ...'rmv_eig_pre_cov_1_epsilon_200_locs2_3sphere',...
    'rmv_aniso_eig_pre_leadfield_1_locs2_3sphere',...
    'rmv_aniso_eig_pre_cov_1_locs2_3sphere',...
    'rmv_aniso_locs2_3sphere',...
    'lcmv_locs2_3sphere',...
    'lcmv_eig_cov_0_locs2_3sphere',...
    'lcmv_eig_cov_1_locs2_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = '-final';
params(k).matched = false;
k = k+1;

params(k).beamformer_configs = {...
    'rmv_epsilon_150_locs2_3sphere',...
    'rmv_aniso_locs2_3sphere',...
    'lcmv_locs2_3sphere',...
    'lcmv_eig_cov_0_locs2_3sphere',...
    'lcmv_eig_cov_1_locs2_3sphere',...
    'lcmv_eig_leadfield_0_locs2_3sphere',...
    'lcmv_eig_leadfield_1_locs2_3sphere',...
    'lcmv_eig_filter_0_locs2_3sphere',...
    'lcmv_eig_filter_1_locs2_3sphere',...
    'lcmv_eig_cov_leadfield_0_locs2_3sphere',...
    'lcmv_eig_cov_leadfield_1_locs2_3sphere',...
    'lcmv_reg_eig_3sphere'
    };
params(k).tag = '-lcmv';
params(k).matched = false;
k = k+1;

% params(k).beamformer_configs = {...
%     'rmv_epsilon_100_locs2_3sphere',...
%     'rmv_epsilon_150_locs2_3sphere',...
%     'rmv_epsilon_200_locs2_3sphere',...
%     'rmv_eig_pre_cov_0_epsilon_100_locs2_3sphere',...
%     'rmv_eig_pre_cov_0_epsilon_150_locs2_3sphere',...
%     'rmv_eig_pre_cov_0_epsilon_200_locs2_3sphere',...
%     'rmv_eig_pre_cov_1_epsilon_100_locs2_3sphere',...
%     'rmv_eig_pre_cov_1_epsilon_150_locs2_3sphere',...
%     'rmv_eig_pre_cov_1_epsilon_200_locs2_3sphere',...
%     };
% params(k).tag = '-eps-variations';
% params(k).matched = false;
% k = k+1;

for i=1:length(params)
    data_set = SimDataSetEEG(...
        sim_name,...
        source_name,...
        0,...
        'iter',1);
    
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        295,...
        'savetag',params(i).tag,...
        'matched',params(i).matched,...
        'metricx','input snr',...
        'metricy','output sinr',...
        'snrs',-20:5:20,...
        'force',force...
        );
    
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        295,...
        'savetag',params(i).tag,...
        'matched',params(i).matched,...
        'metricx','input snr',...
        'metricy','output snr',...
        'snrs',-20:5:20,...
        'force',force...
        );
    
    
    plot_metric_output_vs_input_group(...
        data_set,...
        params(i).beamformer_configs,...
        400,...
        'savetag',params(i).tag,...
        'matched',params(i).matched,...
        'metricx','input snr',...
        'metricy','output isnr',...
        'snrs',-20:5:20,...
        'force',force...
        );
end
end
