%% recompute_beamformer_output

% scenario = 'test';
scenario = 'mult_cort_src_17hd_lag40_eig';

%% test
switch scenario
    case 'test'
        data_set = SimDataSetEEG(...
            'sim_data_test',...
            'mult_cort_src_3',...
            0,...
            'iter',1);
        
        beamformers = {...
            'lcmv',...
            'lcmv_eig_filter_2',...
            'lcmv_reg_eig',...
            };
        
    case 'mult_cort_src_17hd_lag40_eig'
        % recompute eigenspace results for mult_cort_src_17hd_lag40
        
        data_set = SimDataSetEEG(...
            'sim_data_bemhd_1_100t',...
            'mult_cort_src_17hd_lag40',...
            0,...
            'iter',1);
        
        beamformers = {...
            'rmv_eig_pre_cov_0_epsilon_20',...
            'rmv_eig_pre_cov_1_epsilon_20',...
            'lcmv_eig_cov_0',...
            'lcmv_eig_cov_1',...
            'rmv_eig_pre_cov_0_epsilon_150_3sphere',...
            'rmv_eig_pre_cov_1_epsilon_150_3sphere',...
            'rmv_aniso_eig_pre_cov_1_3sphere',...
            'lcmv_eig_cov_0_3sphere',...
            'lcmv_eig_cov_1_3sphere',...
            };
    otherwise
        error('unknown scenario: %s',scenario);
end

beamformer_output(data_set,beamformers);