%% run_simulation_3.m -- All example simulations
% Runs all the simulations using mult_cort_src_3

clear all;
close all;
clc;

%% Update AET, just in case
util.update_aet();

%% Initialize the Advanced EEG Toolbox
aet_init
k = 1;

%% Set up scripts to run


scripts(k).func = @simulation_data;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3');
scripts(k).vars = {cfg};
k = k+1;

%% Ex1
% Exact leadfield case

% SNR sweepts at differnt epsilon values
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

scripts(k).func = @simulation_ex1_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_1',...
    'sim_file_out',         'mult_cort_src_3_ex1_snr_eps_10');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex1_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_3',...
    'sim_file_out',         'mult_cort_src_3_ex1_snr_eps_200');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex1_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_4',...
    'sim_file_out',         'mult_cort_src_3_ex1_snr_eps_400');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex1_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_5',...
    'sim_file_out',         'mult_cort_src_3_ex1_snr_eps_many');
scripts(k).vars = {cfg};
k = k+1;

% Epsilon sweeps at different SNR ratios
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

scripts(k).func = @simulation_ex1_epsilon;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_1',...
    'cur_snr',              -10,...
    'epsilon',              [0 800],...
    'n_epsilon',            10,...
    'sim_file_out',         'mult_cort_src_3_ex1_epsilon_0_800_snr-10');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex1_epsilon;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_1',...
    'cur_snr',              10,...
    'epsilon',              [0 800],...
    'n_epsilon',            10,...
    'sim_file_out',         'mult_cort_src_3_ex1_epsilon_0_800_snr10');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex1_epsilon;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_1',...
    'cur_snr',              20,...
    'epsilon',              [0 800],...
    'n_epsilon',            10,...
    'sim_file_out',         'mult_cort_src_3_ex1_epsilon_0_800_snr20');
scripts(k).vars = {cfg};
k = k+1;

%% Ex2
% Mismatched case

% SNR sweepts at differnt epsilon values
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

scripts(k).func = @simulation_ex2_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_2',...
    'sim_file_out',         'mult_cort_src_3_ex2_snr_eps_10');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex2_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_3',...
    'sim_file_out',         'mult_cort_src_3_ex2_snr_eps_200');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex2_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_4',...
    'sim_file_out',         'mult_cort_src_3_ex2_snr_eps_400');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex2_snr;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_5',...
    'sim_file_out',         'mult_cort_src_3_ex2_snr_eps_many');
scripts(k).vars = {cfg};
k = k+1;

% Epsilon sweeps at different SNR ratios
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

scripts(k).func = @simulation_ex2_epsilon;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_1',...
    'cur_snr',              -10,...
    'epsilon',              [0 800],...
    'n_epsilon',            10,...
    'sim_file_out',         'mult_cort_src_3_ex2_epsilon_0_800_snr-10');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex2_epsilon;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_1',...
    'cur_snr',              10,...
    'epsilon',              [0 800],...
    'n_epsilon',            10,...
    'sim_file_out',         'mult_cort_src_3_ex2_epsilon_0_800_snr10');
scripts(k).vars = {cfg};
k = k+1;

scripts(k).func = @simulation_ex2_epsilon;
cfg = struct(...
    'sim_data',             'sim_data_1',...
    'sim_src_parameters',   'src_param_mult_cortical_source_3',...
    'sim_beam',             'sim_beam_1',...
    'cur_snr',              20,...
    'epsilon',              [0 800],...
    'n_epsilon',            10,...
    'sim_file_out',         'mult_cort_src_3_ex2_epsilon_0_800_snr20');
scripts(k).vars = {cfg};
k = k+1;

%% Run the scripts
aet_run_scripts( scripts );
