function [out] = report_setup(name)
%
%   name
%       name of report

% Set up the filename
[pathstr,filename,~] = fileparts(name);
ext = '.org';
out.filename = fullfile(pathstr,[filename ext]);

% Create a new file for the report, overwrite existing
fileID = fopen(out.filename, 'w+');
header = [...
    '#+TITLE:     ' filename '\n'...
    '#+AUTHOR:    Phil Chrapka\n'...
    '#+EMAIL:     chrapkpk@mcmaster.ca\n'...
    '#+DATE:      March 30, 2015\n'...
    '\n'...
    '#+DESCRIPTION:\n'...
    '#+KEYWORDS:\n'...
    '#+LANGUAGE:  en\n'...
    '#+OPTIONS:   H:3 num:t toc:nil \\n:nil @:t ::t |:t ^:t -:t f:t *:t <:t\n'...
    '#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc\n'...
    '#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js\n'...
    '#+EXPORT_SELECT_TAGS: export\n'...
    '#+EXPORT_EXCLUDE_TAGS: noexport\n'...
    '#+LINK_UP:   \n'...
    '#+LINK_HOME: \n'...
    '#+XSLT:\n'...
    '\n'...
    '#+latex_header: \\usepackage[left=1in,top=1in,right=1in,bottom=1in]{geometry}\n'...
    '#+latex_header: \\usepackage{graphicx}\n'...
    '#+latex_header: \\graphicspath{{../}}\n'...
    '#+latex_header: \\usepackage{caption}\n'...
    '#+latex_header: \\usepackage{subcaption}\n'...
    '\n'...
    '#+latex: \\clearpage\n' ...
    '\n'...
];
fprintf(fileID, header);
fclose(fileID);

end