function [subfigure] = report_subfigure(caption, gfxoptions, imgfile, label, subfigoptions)

subfigure = ['\\begin{subfigure}[h]{' subfigoptions '}\n'...
    '\t\\includegraphics[' gfxoptions ']{' imgfile '}\n'...
    '\t\\caption{' caption '}\n'...
    '\t\\label{' label '}\n'...
    '\\end{subfigure}\n'...
    ];
end