function [subfloat] = report_subfloat(name, gfxoptions, imgfile, label)

subfloat = ['\\subfloat[' name ']{\n'...
    '\t\\includegraphics[' gfxoptions ']{' imgfile '}\n'...
    '\t\\label{' label '}\n'...
    '}\n'...
    ];

end