function [fig] = report_figure_matched_mismatched(matched, mismatched)

fig = ['#+begin_latex\n'...
    '\\begin{figure*}[h]\n'...
    '\\centering\n'...
    '\n'...
    '\\begin{tabular}{cccc}\n'...
    '\n'...
    '%% row 1\n'...
    '& & \\textbf{Matched model} & \\textbf{Mismatched model}\\\\ \n\n'...
    ];

pattern = '(?<=s)\d+';
result = regexp(matched{1}, pattern, 'match');
sample = result{1};

subfigoptions = '0.20\\textwidth';
gfxoptions = 'width=\\textwidth';

% MVB fig
imgfile1 = lumberjack.strfindlist(matched, 'lcmv_power3d');
imgfile2 = lumberjack.strfindlist(mismatched, 'lcmv_3sphere_power3d');
fig = [fig...
    '&\n'...
    '&\n'...
    report_subfigure('MVB', gfxoptions, imgfile1, 'fig_mvb_matched', subfigoptions)...
    '&\n'...
    report_subfigure('MVB', gfxoptions, imgfile2, 'fig_mvb_mismatched', subfigoptions)...
    '\\\\\n\n'...
    ];

fig = [fig...
    '%% row 2\n'...
    '\\textbf{Matched model} & \\textbf{Mismatched model} & &\\\\ \n\n'...
    ];

% Regularized MVB fig
imgfile1 = lumberjack.strfindlist(matched, 'lcmv_reg_eig_power3d');
imgfile2 = lumberjack.strfindlist(mismatched, 'lcmv_reg_eig_3sphere_power3d');
% Eigenspace-based MVB fig
imgfile3 = lumberjack.strfindlist(matched, 'lcmv_eig_1_power3d');
imgfile4 = lumberjack.strfindlist(mismatched, 'lcmv_eig_1_3sphere_power3d');
fig = [fig...
    report_subfigure('Regularized MVB', gfxoptions, imgfile1, 'fig_mvb_reg_matched', subfigoptions)...
    '&\n'...
    report_subfigure('Regularized MVB', gfxoptions, imgfile2, 'fig_mvb_reg_mismatched', subfigoptions)...
    '&\n'...
    report_subfigure('Eigenspace-based MVB', gfxoptions, imgfile3, 'fig_mvb_eig_matched', subfigoptions)...
    '&\n'...
    report_subfigure('Eigenspace-based MVB', gfxoptions, imgfile4, 'fig_mvb_eig_mismatched', subfigoptions)...
    '\\\\\n\n'...
    ];

% RMVB iso fig
imgfile1 = lumberjack.strfindlist(matched, 'rmv_epsilon_20_power3d');
imgfile2 = lumberjack.strfindlist(mismatched, 'rmv_epsilon_150_3sphere_power3d');
% RMVB aniso fig
imgfile4 = lumberjack.strfindlist(mismatched, 'rmv_aniso_3sphere_power3d');
fig = [fig...
    report_subfigure('RMVB, isotropic uncertainty', gfxoptions, imgfile1, 'fig_rmvb_matched', subfigoptions)...
    '&\n'...
    report_subfigure('RMVB, isotropic uncertainty', gfxoptions, imgfile2, 'fig_rmvb_mismatched', subfigoptions)...
    '&\n'...
    '&\n'...
    report_subfigure('RMVB, anisotropic uncertainty', gfxoptions, imgfile4, 'fig_rmvb_aniso_mismatched', subfigoptions)...
    '\\\\\n\n'...
    ];

fig = [fig ...
    '\\end{tabular}\n'...
    '\n'...
    '\\caption{Simulation results for sample ' sample '}\n'...
    '\\label{fig_sim}\n'...
    '\\end{figure*}\n'...
    '#+end_latex'...
    ];

end