%% beampattern_single_paper

voxel_idx = 295;
snr = 0;

% Set up simulation info
data_set = SimDataSetEEG(...
    'sim_data_bem_1_100t_1000s',...
    'single_cort_src_1',...
    snr,...
    'iter',1);


%% ==== MATCHED LEADFIELD ====

% Set up beamformer data sets to process
beam_cfgs = {...
    'rmv_epsilon_20',...
    ...'rmv_epsilon_50',...
    ...'rmv_eig_post_0_epsilon_20',...
    ...'rmv_eig_post_0_epsilon_50',...
    'lcmv',...
    'lcmv_eig_0',...
    'lcmv_reg_eig'...
    }; 

%% Plot the beampattern
outputfiles = compute_beampattern(data_set,beam_cfgs,voxel_idx);

for i=1:length(outputfiles)
    vobj = ViewSources(outputfiles{i});
    cfgplt = [];
    cfgplt.db = false;
    cfgplt.normalize = false;
    vobj.plot('beampattern',cfgplt);
    
    cfgplt = [];
    vobj.plot('beampattern3d',cfgplt);
end

%% ==== MISMATCHED LEADFIELD ====

% Set up beamformer data sets to process
beam_cfgs = {...
    ...'rmv_epsilon_50_3sphere',...
    ...'rmv_epsilon_100_3sphere',...
    'rmv_epsilon_150_3sphere',...
    ...'rmv_epsilon_200_3sphere',...
    'rmv_aniso_3sphere',...
    ...'rmv_eig_post_0_epsilon_50_3sphere',...
    ...'rmv_eig_post_0_epsilon_100_3sphere',...
    ...'rmv_eig_post_0_epsilon_150_3sphere',...
    ...'rmv_eig_post_0_epsilon_200_3sphere',...
    ...'rmv_aniso_eig_0_3sphere',...
    'lcmv_3sphere',...
    'lcmv_eig_0_3sphere',...
    'lcmv_reg_eig_3sphere'};

%% Plot the beampattern
outputfiles = compute_beampattern(data_set,beam_cfgs,voxel_idx);

for i=1:length(outputfiles)
    vobj = ViewSources(outputfiles{i});
    cfgplt = [];
    cfgplt.db = false;
    cfgplt.normalize = false;
    vobj.plot('beampattern',cfgplt);
    
    cfgplt = [];
    vobj.plot('beampattern3d',cfgplt);
end
